-- AlterTable
ALTER TABLE "User" ADD COLUMN     "billingResetDay" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "includedMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "overageRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
